name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_linux:
    name: Test Linux Default
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run:  |
        sudo apt install coinor-cbc
    - name: Build
      run: cargo test --no-run --verbose
    - name: Run tests
      run: cargo test --verbose

  test_linux_coinor:
    name: Test Linux Coinor CBC
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run:  |
        sudo apt install coinor-libcbc-dev coinor-cbc
    - name: Build
      run: cargo test --no-run --verbose --features "native_coin_cbc minilp"
    - name: Run tests
      run: cargo test --verbose --features "native_coin_cbc minilp"
  
  test_windows:
    name: Test Windows Default
    runs-on: windows-latest    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run:  |
        mkdir C:\Cbc
        curl https://ampl.com/dl/open/cbc/cbc-win64.zip --output Cbc-2.9.zip
        7z x "Cbc-2.9.zip" -o"Cbc"
        $SUB= '' + (Get-Location) + '\Cbc'
        echo $SUB
        echo $SUB | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose